<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="clk_edumip">

<xacro:property name="wheel_separation" value="0.070"/>
<xacro:property name="wheel_radius" value="0.034" />
<xacro:property name="wheel_width" value="0.010" />
<xacro:property name="body_height" value="0.1" />
<xacro:property name="body_width" value="0.050" />
<xacro:property name="body_length" value="0.035" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

<xacro:macro name="wheel" params="postfix reflect">
   <link name="wheel${postfix}">
     <visual>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
         </geometry>
      </visual>
      <collision>
	 <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
         </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <!--mass>0.05</mass> -->
	<mass value="0.05"/>
	<inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
   </link>
</xacro:macro>

<xacro:macro name="wheel_joint" params="postfix reflect">
   <joint name="joint${postfix}" type="continuous">
       <parent link="edumip_body"/>
       <child link="wheel${postfix}"/>
       <origin xyz="0 ${reflect*wheel_separation/2} ${wheel_radius}" rpy="${3.1459/2} 0 0" />
       <axis xyz="0 0 1" />
   </joint>
</xacro:macro>

<link name="edumip_body">
  <visual>
      <origin xyz="0 0 ${body_height/2+wheel_radius}" rpy="0 -0.17 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>	
      </geometry>
      <material name="blue"/>
   </visual>
   <collision>
      <geometry>
         <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${body_height/2+wheel_radius}" rpy="0 -0.17 0" />
   </collision>
   <inertial>
     <origin xyz="0 0 -1" rpy="0 -0.17 0" />
     <!--mass>0.5</mass-->
     <mass value="0.5"/>
     <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
   </inertial>
     
</link>

<xacro:wheel postfix="L" reflect="1" />
<xacro:wheel postfix="R" reflect="-1" />

<xacro:wheel_joint postfix="L" reflect="1" />
<xacro:wheel_joint postfix="R" reflect="-1" />

 <gazebo reference="edumip_body">
   <material>Gazebo/Blue</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelR">
   <material>Gazebo/Green</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelL">
   <material>Gazebo/Red</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>

</robot>


